# permissions for end users to view testruns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: testrun-viewer-role
rules:
- apiGroups:
  - graphnode.streamingfast.io
  resources:
  - testruns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - graphnode.streamingfast.io
  resources:
  - testruns/status
  verbs:
  - get
